"""Automatic validation-selected generation and final-VQE checkpoint sweeps."""
from __future__ import annotations
from pathlib import Path
from typing import Any, Mapping, Sequence
import pandas as pd
import plotly.express as px
import streamlit as st
from vanguard_copilot.final_state_summary import build_final_state_summary, save_final_state_summary
from vanguard_copilot.five_asset_hubo import load_five_asset_snapshot
from vanguard_copilot.higher_moment_extension import SourceMomentData, load_source_snapshot
from vanguard_copilot.source_datasets import load_sector_dataset_bundle
from vanguard_copilot.source_hubo_models import exact_source_hubo_report
from vanguard_copilot.validated_generation_sweep import SELECTION_OBJECTIVES, config_from_validated_sweep, validated_generation_sweep
from vanguard_copilot.vqe_checkpoint_sweep import run_vqe_checkpoint_sweep

def _portfolio_row(label,record,gt):
    return {"Method":label,"Bitstring":record["bitstring"],"Matches ground truth":int(record.get("state_index",-1))==int(gt["state_index"]),"Budget breach":float(record.get("budget_breach",0.0)),"Expected return":float(record["expected_return"]),"Return Δ vs GT":float(record["expected_return"]-gt["expected_return"]),"Volatility":float(record["volatility"]),"Volatility Δ vs GT":float(record["volatility"]-gt["volatility"]),"Sharpe":float(record["sharpe_ratio"]),"Sharpe Δ vs GT":float(record["sharpe_ratio"]-gt["sharpe_ratio"]),"|Sharpe error|":float(abs(record["sharpe_ratio"]-gt["sharpe_ratio"])),"Hamiltonian energy":float(record.get("total_energy",0.0))}
def _render_training_comparison(exact_report,vqe_report):
    gt=exact_report["financial_reference"]; feasible=exact_report["best_admissible_hamiltonian_state"]; unrestricted=exact_report["hamiltonian_ground_state"]; rows=[_portfolio_row("Financial ground truth (exact max Sharpe)",gt,gt),_portfolio_row("Exact feasible learned-HUBO ground",feasible,gt),_portfolio_row("Unrestricted Hamiltonian ground",unrestricted,gt)]
    if vqe_report is not None: rows.append(_portfolio_row("Selected finite-shot VQE",vqe_report["selected"],gt))
    st.subheader("Ground-truth comparison — training universe"); st.dataframe(pd.DataFrame(rows),use_container_width=True,hide_index=True)
def _ground_truth_records(datasets,config): return [exact_source_hubo_report(data,config)["financial_reference"] for data in datasets]
def _sector_frame(details,ground_truth):
    rows=[]
    for detail,gt in zip(details,ground_truth): rows.append({"Sector":detail["name"],"HUBO ground feasible":detail["ground_feasible"],"HUBO budget breach":detail["budget_breach"],"HUBO return":detail["expected_return"],"GT return":gt["expected_return"],"Return Δ vs GT":detail["expected_return"]-gt["expected_return"],"HUBO volatility":detail["volatility"],"GT volatility":gt["volatility"],"Volatility Δ vs GT":detail["volatility"]-gt["volatility"],"HUBO Sharpe":detail["sharpe"],"GT Sharpe":gt["sharpe_ratio"],"Sharpe Δ vs GT":detail["sharpe"]-gt["sharpe_ratio"],"|Sharpe error|":abs(detail["sharpe"]-gt["sharpe_ratio"]),"Exact GT recovered":int(detail["ground_state_index"])==int(gt["state_index"])})
    return pd.DataFrame(rows)
def _render_sector_comparison(title,frame):
    st.subheader(title); st.dataframe(frame,use_container_width=True,hide_index=True); cols=st.columns(5); cols[0].metric("Exact GT recovery",f"{frame['Exact GT recovered'].mean():.1%}"); cols[1].metric("Mean |Sharpe error|",f"{frame['|Sharpe error|'].mean():.5f}"); cols[2].metric("Mean return Δ",f"{frame['Return Δ vs GT'].mean():+.2%}"); cols[3].metric("Mean volatility Δ",f"{frame['Volatility Δ vs GT'].mean():+.2%}"); cols[4].metric("Feasibility",f"{frame['HUBO ground feasible'].mean():.1%}")
st.set_page_config(page_title="Automatic HUBO Selection",page_icon="🎯",layout="wide"); st.title("Automatic HUBO Generation + VQE Selection"); st.caption("Select G* from one cached CMA-ES trajectory, then sweep final VQE optimizer budgets on the fixed learned Hamiltonian.")
with st.sidebar:
    st.header("Automatic selection"); qubits=st.radio("Full-tensor HUBO size",options=[12,15],horizontal=True); objective_label=st.selectbox("Validation selection objective",options=list(SELECTION_OBJECTIVES.values()),index=list(SELECTION_OBJECTIVES).index("efficient_sharpe")); objective=next(k for k,v in SELECTION_OBJECTIVES.items() if v==objective_label); checkpoints=st.multiselect("Generation checkpoints",options=[5,10,20,30,50,75,100],default=[5,10,20,30,50]); population_size=st.select_slider("CMA-ES population",options=[6,8,10,12,16,20],value=12); tolerance_pct=st.slider("Near-optimal Sharpe tolerance (%)",0.1,5.0,1.0,0.1,disabled=objective!="efficient_sharpe"); seed=st.number_input("Random seed",min_value=0,max_value=1_000_000,value=42,step=1); st.divider(); data_path=st.text_input("Sector dataset path (optional)",value="",placeholder="data/portfolio_data_2.npz"); run_vqe=st.checkbox("Run final VQE optimizer checkpoint sweep",value=True); vqe_checkpoints=st.multiselect("Final VQE optimizer checkpoints",options=[20,40,60,80,120,160,200],default=[20,40,60,80,120] if qubits==12 else [20,40,60,80],disabled=not run_vqe); shots=st.select_slider("Final VQE shots",options=[1024,2048,4096,8192],value=4096); run=st.button("Run automatic selection",type="primary",use_container_width=True)
if not run: st.info("Choose generation and VQE checkpoints, then run the pipeline. Held-out sectors are not used to select G*."); st.stop()
if not checkpoints: st.error("Select at least one generation checkpoint."); st.stop()
if run_vqe and not vqe_checkpoints: st.error("Select at least one final VQE optimizer checkpoint."); st.stop()
try: bundle=load_sector_dataset_bundle(Path(data_path).expanduser() if data_path.strip() else None)
except FileNotFoundError as exc: st.error(str(exc)); st.code("python src/fetch_sector_data.py",language="bash"); st.stop()
train_data=load_source_snapshot() if qubits==12 else load_five_asset_snapshot()
with st.spinner(f"Running {qubits}-qubit generation selection..."):
    sweep=validated_generation_sweep(train_data,bundle["validation"],bundle["held_out"],validation_names=bundle["validation_names"],held_out_names=bundle["held_out_names"],checkpoints=checkpoints,population_size=int(population_size),seed=int(seed),objective=objective,near_optimal_tolerance=float(tolerance_pct)/100.0); learned_config=config_from_validated_sweep(sweep); exact_report=exact_source_hubo_report(train_data,learned_config)
selected_candidate=next(c for c in sweep["candidates"] if c["generation"]==sweep["selected_generation"]); validation_gt=_ground_truth_records(bundle["validation"],learned_config); held_out_gt=_ground_truth_records(bundle["held_out"],learned_config); validation_frame=_sector_frame(selected_candidate["validation_details"],validation_gt); held_out_frame=_sector_frame(sweep["held_out_details"],held_out_gt); vqe_sweep=None; vqe_report=None
if run_vqe:
    with st.spinner("Sweeping final VQE optimizer checkpoints on the fixed selected Hamiltonian..."):
        vqe_sweep=run_vqe_checkpoint_sweep(train_data,learned_config,vqe_checkpoints,shots=int(shots),seed=int(seed)); vqe_report=vqe_sweep["selected_report"]
final_summary=build_final_state_summary(qubits=int(qubits),sweep=sweep,exact_report=exact_report,vqe_report=vqe_report)
if vqe_sweep is not None: final_summary["vqe_checkpoint_sweep"]={"selected_optimizer_evaluations":int(vqe_sweep["selected_maxiter"]),"selection_reason":str(vqe_sweep["selection_reason"]),"checkpoints":vqe_sweep["checkpoints"]}
st.session_state["latest_hubo_selection_summary"]=final_summary; summary_path=save_final_state_summary(final_summary); st.success(f"Selected G* = {sweep['selected_generation']} using “{sweep['objective_label']}”."); st.caption(bundle["split_note"]); st.caption(f"Final-state summary saved to `{summary_path}`.")
summary=st.columns(6); summary[0].metric("Qubits",str(qubits)); summary[1].metric("Selected G*",str(sweep["selected_generation"])); summary[2].metric("CMA evaluations",str(sweep["training_evaluations"])); summary[3].metric("Validation Sharpe",f"{sweep['selected_validation_metrics']['mean_sharpe']:.4f}"); summary[4].metric("Held-out Sharpe",f"{sweep['held_out_metrics']['mean_sharpe']:.4f}"); summary[5].metric("Held-out GT recovery",f"{held_out_frame['Exact GT recovered'].mean():.1%}")
st.subheader("Generation checkpoint comparison"); generation_frame=pd.DataFrame([{"Generation":c["generation"],"Selected":c["generation"]==sweep["selected_generation"],"Pareto efficient":c["pareto_efficient"],"Validation return":c["validation_mean_return"],"Validation volatility":c["validation_mean_volatility"],"Validation Sharpe":c["validation_mean_sharpe"],"Feasibility rate":c["validation_feasibility_rate"],"Training elapsed":c["training_elapsed_seconds"]} for c in sweep["candidates"]]); st.dataframe(generation_frame,use_container_width=True,hide_index=True); fig=px.scatter(generation_frame,x="Validation volatility",y="Validation return",size="Generation",color="Validation Sharpe",text="Generation",title="Validation return-risk frontier"); st.plotly_chart(fig,use_container_width=True)
st.subheader("Selected learned coefficients"); st.dataframe(pd.DataFrame([{"Coefficient":k,"Value":v} for k,v in sweep["selected_lambdas"].items()]),hide_index=True,use_container_width=True); _render_sector_comparison("Validation sectors — selected G* versus exact ground truth",validation_frame); _render_sector_comparison("Held-out sectors — selected G* versus exact ground truth",held_out_frame); _render_training_comparison(exact_report,vqe_report)
if vqe_sweep is not None:
    st.subheader("Final VQE optimizer checkpoint comparison"); vqe_frame=pd.DataFrame([{"Optimizer evaluations":row["maxiter"],"Selected":row["maxiter"]==vqe_sweep["selected_maxiter"],"Bitstring":row["bitstring"],"Optimality gap":row["optimality_gap"],"Exact HUBO ground recovered":row["exact_hubo_ground_recovered"],"Financial GT recovered":row["financial_ground_truth_recovered"],"Feasible probability mass":row["feasible_probability_mass"],"Exact-ground probability":row["exact_ground_probability"],"Sharpe":row["sharpe_ratio"],"Runtime":row["runtime_seconds"],"Classical fallback":row["classical_fallback_used"]} for row in vqe_sweep["checkpoints"]]); st.dataframe(vqe_frame,use_container_width=True,hide_index=True); st.success(f"Selected final VQE budget = {vqe_sweep['selected_maxiter']} optimizer evaluations: {vqe_sweep['selection_reason']}.")
st.caption("G* is selected without held-out leakage. VQE optimizer checkpoints tune quantum-solver effort only after the financial Hamiltonian is fixed.")
