"""Co-pilot summary page for the latest automatic HUBO final state."""
from __future__ import annotations
import pandas as pd,streamlit as st
from vanguard_copilot.final_state_summary import load_final_state_summary
st.set_page_config(page_title="Final State Summary",page_icon="📌",layout="wide");st.title("Final Selected State Summary");st.caption("Compact co-pilot view of the most recent automatic full-tensor HUBO selection and final quantum state.")
summary=st.session_state.get("latest_hubo_selection_summary") or load_final_state_summary()
if summary is None:st.info("No automatic HUBO result has been saved yet. Run **Automatic HUBO Generation Selection** first.");st.stop()
final_state=summary["final_state"];gt=summary["financial_ground_truth"];exact=summary["exact_feasible_hubo_ground"];held=summary["held_out"];val=summary["validation"];st.success(f"{summary['model']} · selected G* = {summary['selected_generation']} · selection rule: {summary['selection_objective']}")
c=st.columns(7);c[0].metric("Final state source",summary["final_state_source"]);c[1].metric("Final bitstring",final_state["bitstring"]);c[2].metric("Expected return",f"{final_state['expected_return']:.2%}");c[3].metric("Volatility",f"{final_state['volatility']:.2%}");c[4].metric("Sharpe",f"{final_state['sharpe_ratio']:.4f}");c[5].metric("Budget breach",f"${final_state['budget_breach']:,.2f}");c[6].metric("Matches financial GT",str(final_state["matches_financial_ground_truth"]))
st.subheader("Final allocation");st.dataframe(pd.DataFrame([{"Asset":asset,"Weight":weight} for asset,weight in final_state["weights"].items()]).style.format({"Weight":"{:.1%}"}),hide_index=True,use_container_width=True)
st.subheader("Ground-truth and exact-ground comparison");comparison=pd.DataFrame([{"State":"Financial ground truth (exact max Sharpe)","Bitstring":gt["bitstring"],"Expected return":gt["expected_return"],"Volatility":gt["volatility"],"Sharpe":gt["sharpe_ratio"],"Budget breach":0.0},{"State":"Exact feasible learned-HUBO ground","Bitstring":exact["bitstring"],"Expected return":exact["expected_return"],"Volatility":exact["volatility"],"Sharpe":exact["sharpe_ratio"],"Budget breach":exact["budget_breach"]},{"State":summary["final_state_source"],"Bitstring":final_state["bitstring"],"Expected return":final_state["expected_return"],"Volatility":final_state["volatility"],"Sharpe":final_state["sharpe_ratio"],"Budget breach":final_state["budget_breach"]}]);st.dataframe(comparison.style.format({"Expected return":"{:.2%}","Volatility":"{:.2%}","Sharpe":"{:.5f}","Budget breach":"${:,.2f}"}),hide_index=True,use_container_width=True)
d=st.columns(3);d[0].metric("Return Δ vs GT",f"{final_state['return_difference_vs_ground_truth']:+.2%}");d[1].metric("Volatility Δ vs GT",f"{final_state['volatility_difference_vs_ground_truth']:+.2%}");d[2].metric("Sharpe Δ vs GT",f"{final_state['sharpe_difference_vs_ground_truth']:+.5f}")
st.subheader("Validation and held-out summary");performance=pd.DataFrame([{"Split":"Validation","Mean return":val["mean_return"],"Mean volatility":val["mean_volatility"],"Mean Sharpe":val["mean_sharpe"],"Mean |Sharpe error|":val["mean_sharpe_abs_error"],"Feasibility":val["feasibility_rate"],"Mean budget breach":val["mean_budget_breach"]},{"Split":"Held-out","Mean return":held["mean_return"],"Mean volatility":held["mean_volatility"],"Mean Sharpe":held["mean_sharpe"],"Mean |Sharpe error|":held["mean_sharpe_abs_error"],"Feasibility":held["feasibility_rate"],"Mean budget breach":held["mean_budget_breach"]}]);st.dataframe(performance,use_container_width=True,hide_index=True)
st.subheader("Learned HUBO coefficients");st.dataframe(pd.DataFrame([{"Coefficient":key,"Value":value} for key,value in summary["selected_lambdas"].items()]),hide_index=True,use_container_width=True)
if summary["vqe"] is not None:
    vqe=summary["vqe"];st.subheader("Final VQE diagnostics");q=st.columns(6);q[0].metric("Status",vqe["status"]);q[1].metric("Optimizer evaluations",str(vqe.get("optimizer_evaluations","—")));q[2].metric("Optimality gap",f"{vqe['optimality_gap']:.8f}");q[3].metric("Feasible mass",f"{100*vqe['feasible_probability_mass']:.2f}%");q[4].metric("Exact HUBO ground",str(vqe["exact_hubo_ground_recovered"]));q[5].metric("Classical fallback",str(vqe["classical_fallback_used"]))
st.caption("Financial ground truth is the exact feasible maximum-Sharpe portfolio. Held-out sectors are not used to select G* or the HUBO coefficients.")
